version: '3.8'

services:
  postgres-aggregator:
    image: postgres:latest
    container_name: postgres-aggregator
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      #      my local application pgAdmin application was running on port 5432, so I had to change the port to 5433 and the other application is running on 5433
      - '5434:5432'

