spring:
  application:
    name: Recommender-System-Aggregator

  datasource:
    url: jdbc:postgresql://localhost:5434/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: localhost:9093
    consumer:
      group-id: aggregator-service
    properties:
      schema:
        registry:
          url: http://localhost:8081
      specific:
        avro:
          reader: true

  flyway:
    locations: classpath:db/migration
    url: jdbc:postgresql://localhost:5433/postgres
    user: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    enabled: true
  config:
    import: classpath:kafka-topics.yaml

